// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXXmZu0bHNCwosu9xPR8WBbUlbYBbNHA4',
    appId: '1:827323694886:web:4e6e7e32fb86921b084be7',
    messagingSenderId: '827323694886',
    projectId: 'serviz-52296',
    authDomain: 'serviz-52296.firebaseapp.com',
    storageBucket: 'serviz-52296.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3badBs9mf_NPCWIjoREAHYmqd_E6m7D4',
    appId: '1:827323694886:android:f77f6e78084baef7084be7',
    messagingSenderId: '827323694886',
    projectId: 'serviz-52296',
    storageBucket: 'serviz-52296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVkdzlFU7FKjrH1Tb0aEWvGdME5jG71c',
    appId: '1:827323694886:ios:3e14924c8e4ab061084be7',
    messagingSenderId: '827323694886',
    projectId: 'serviz-52296',
    storageBucket: 'serviz-52296.appspot.com',
    iosClientId: '827323694886-imvrbe8bopcfqs9u6on0fqfndecuateh.apps.googleusercontent.com',
    iosBundleId: 'com.example.serviz',
  );
}
